[build]
  base = "docs"
  publish = "build/html"
  command = "python -m pip install -r requirements-docs.txt && python -m sphinx -b html source build/html"

[build.environment]
  PYTHON_VERSION = "3.11"

