[project]
name = "smartdoc"
version = "0.1.0"
description = "A quality scorer for OAS files"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.scripts]
smartdoc = "smartdoc.cli:app"